### ISSUE TITLE
Deprecated use of size()

### ISSUE THREAD

**Issue by RicardoAratani** [neo4j-graphacademy/app-nodejs#10]
The repository still contains code samples using size(), which is deprecated.
The [tutorial](https://graphacademy.neo4j.com/courses/app-nodejs/3-backlog/7-person-view/) has already been updated to use count {}.

**Comment by adam-cowley** [comment]
Thanks for spotting this. I have updated this in fa74bfcbe5c254219d9e49f5fc7cdae8dd6d00f5.  A classic case of _"Do what I say, not what I do"_!
