### ISSUE TITLE
Diff 15 can

### ISSUE THREAD

**Issue by RicardoAratani** [neo4j-graphacademy/app-nodejs#11]

**Comment by RicardoAratani** [comment]
Please forgive the poor quality of this issue, I've already closed the training project.
But when trying to apply diff 15 (last one), it complained that 2 hunks couldn't be applied. I was using WebStorm through Gitpod (as a thin client), didn´t realize there was this repo until late, with the branches to check out, so I was applying the patches...

**Comment by adam-cowley** [comment]
Thanks, I'll take a look.  These are more for me to be able to recreate the branches if there is a problem with rebasing rather than something a learner should use.  Hopefully, the branches give you the information you need.
