### ISSUE TITLE
Migrate to typescript

### ISSUE THREAD

**Issue by ramzes13** [neo4j-graphacademy/app-nodejs#3]
I want to know if you plan to migrate this project to typescript.
Thanks

**Comment by adam-cowley** [comment]
There are no plans at the moment, but all of the code in this repo will work with the types exported by `neo4j-driver`.

If you need inspiration, I have [a few examples on my profile written with typescript](https://github.com/adam-cowley?tab=repositories&q=&type=&language=typescript&sort=).
